ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path,include
from cart import views
app_name="cart"
urlpatterns = [
    path('addtocart/<str:n>',views.addtocart,name="addtocart"),
    path('cartview',views.cartview,name="cartview"),
    path('decrease_quantity/<str:n>/', views.decrease_quantity, name='decrease_quantity'),
    path('trash/<str:n>/', views.trash, name='trash'),
    path('orderform',views.orderform,name="orderform"),
    path('orderview',views.orderview,name="orderview"),


]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path,include
from shop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path,include
from search import views
app_name="search"
urlpatterns = [
    path('',views.search,name="search"),


]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views
app_name="shop"
urlpatterns = [
    path('',views.allcategories,name='allcategories'),
    path('prod/<str:p>/', views.prod, name="prod"),
    path('detail/<str:p>/', views.detail, name="detail"),
    path('register',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout"),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    date_added=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.IntegerField()
    ordered_date=models.DateTimeField(auto_now_add=True)
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")

    def __str__(self):
        return self.product.name


class Account(models.Model):
    acctnum=models.IntegerField()
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()

    def __str__(self):
        return str(self.acctnum)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render
from shop.models import Product
from cart.models import Cart,Account,Order
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

@login_required
def cartview(request):
    u=request.user
    cart = Cart.objects.filter(user=u)
    total=0
    for i in cart:
        total += i.quantity*i.product.price



    return render(request,'cartview.html',{'c':cart,'total':total})





@login_required
def addtocart(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(p.stock > 0):
            cart.quantity+=1
            cart.save()
            p.stock -= 1
            cart.save()
    except:
        if(p.stock>0):
            cart=Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
            p.stock -= 1
            cart.save()
    return cartview(request)

@login_required
def decrease_quantity(request, n):
    p = Product.objects.get(name=n)
    u = request.user

    try:
        cart = Cart.objects.get(user=u, product=p)
        if cart.quantity > 1:
            cart.quantity -= 1
            cart.save()
            p.stock += 1
            cart.save()
        else:
            cart.delete()
            p.stock += 1
            cart.save()
    except Cart.DoesNotExist:
        pass  # Handle the case when the product is not in the cart

    return cartview(request)

@login_required
def trash(request, n):
    p = Product.objects.get(name=n)
    u = request.user

    try:
        cart = Cart.objects.get(user=u, product=p)
        cart.delete()
        p.stock+= cart.quantity
    except:
        pass

    return cartview(request)


@login_required
def orderform(request):
    if (request.method == "POST"):
        a = request.POST['a']
        ph = request.POST['ph']
        an = request.POST['an']

        u=request.user
        cart=Cart.objects.filter(user=u)

        total=0
        for i in cart:
            total += i.quantity * i.product.price


        try:
            num=int(an)
            ac=Account.objects.get(acctnum=num)
            if(ac.amount>=total):
                ac.amount=ac.amount-total
                ac.save()
                for i in cart:
                    o=Order.objects.create(user=u,product=i.product,address=a,phone=ph,no_of_items=i.quantity,order_status="paid")
                    o.save()
                cart.delete()
                msg="Your Order placed successfully"
                return render(request,'orderdetails.html',{'msg':msg})
            else:
                msg = "Insufficient Amount. You can't Place Order"
                return render(request, 'orderdetails.html', {'msg': msg})
        except:
            pass


    return render(request, 'orderform.html')

@login_required
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,"orderview.html",{'o':o,'u':u.username})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

def search(request):
    query=""
    products=None
    if(request.method=="POST"):
        query=request.POST['q']
        if(query):
            products=Product.objects.filter(Q(name_icontains=query)|Q(desc_icontains=query))
    return render(request,'search.html',{'query':query,'p':products})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<!--    <style>-->
<!--        body {-->
<!--            display: flex;-->
<!--            flex-direction: column;-->
<!--            min-height: 100vh;-->
<!--            margin: 0;-->
<!--        }-->

<!--        .container-fluid {-->
<!--            text-align: center; /* Center align content in container */-->
<!--        }-->

<!--        .footer {-->
<!--            margin-top: auto; /* Push the footer to the bottom of the container */-->
<!--            background-color: #f8f9fa; /* Add a background color for better visibility */-->
<!--            padding: 20px 0; /* Add padding for better aesthetics */-->
<!--        }-->
<!--    </style>-->
</head>
<body style="background-color: #f5bd98;">

<header>
    <div class="container-fluid">
        <center><img src="{% static 'images/logo1.jpg' %}" height="120px" width="100px"></center>
    </div>
</header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-top: 20px;">
  <div class="container-fluid" >
    <a class="navbar-brand" href="#">MY SHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:allcategories' %}">HOME</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            ALL CATEGORIES
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:prod' i.name %}">{{i.name}}</a></li>
            {% endfor %}
              </ul>
          {% if user.is_authenticated %}

              <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{%  url 'shop:logout' %}">LOGOUT</a>
        </li>
          {% if user.is_superuser == False %}
           <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"><sub class="ms-1">{{count}}</sub></i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'cart:orderview' %}">YOUR ORDERS</a>
        </li>

          {% endif %}
          {% else %}
          <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:register' %}">REGISTER</a>
        </li>
              <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:login' %}">LOGIN</a>
        </li>


        {% endif %}

        </li>

      </ul>
      <form class="d-flex" method="post" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
<!-- Your page content goes here -->

<footer class="footer" >
    <div class="container-fluid text-center">
        <p>&copy; Myshop pvt ltd. All rights reserved.</p>
    </div>
</footer>

</body>
</html>

ecommerce/templates/cartview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
    <div class="row">
        <h4 class="text-center">Shopping Cart</h4>
        <div class="col-6 border border-1">
            <table class="table table-bordered text-center fs-5" style="border-color: black;">
                <tr>
                    <th colspan="5"> Cart Items</th>
                </tr>
                {% for i in c %}
                <tr>
                    <td><img src="{{i.product.image.url}}" height="150px" width="150px"</td>
                    <td><b>{{i.product.name}}</b><br>
                    <b>ProductID:{{i.product.id}}</b><br>
                    <b> Unit Price:{{i.product.price}}</b><br>
                    <b>Quantity:{{i.quantity}}*{{i.product.price}}</b><br>
                    </td>

                    <td>Subtotal:{{i.subtotal}}</td>

                <td>

                    {% if i.product.stock > 0 %}
                    <a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-circle-plus text-danger"></i></a>
                        <a href="{% url 'cart:decrease_quantity' i.product.name %}"><i class="fa-solid fa-circle-minus text-danger"></i></a>
                    <a href="{% url 'cart:trash' i.product.name %}"><i class="fa-solid fa-trash text-danger"></i></a>


                    {% else %}
                        <a href="{% url 'cart:decrease_quantity' i.product.name %}"><i class="fa-solid fa-circle-minus text-danger"></i></a>
                        <a href="{% url 'cart:trash' i.product.name %}"><i class="fa-solid fa-trash text-danger"></i></a>

                    {% endif %}</td>
                {% endfor %}
            </table>
    </div>


<div class="col-4 border border-1 ms-3 ">
    <table class="table table-bordered text-center fs-5" style="border-color: black; position: relative;"">
    <tr>
        <th colspan ="5">Check Out</th>
    </tr>
        <tr><th>Total:<span style="position:absolute;right:120px" >{{total}}</span></th></tr>
</table>
    <a href="{% url 'cart:orderform' %}" class="btn btn-danger">Place Order</a>
    <a href="{% url 'shop:allcategories' %}" class="btn btn-danger" style="position:relative;right:20px;top: 40px;" >Continue Shopping</a>
        </div>
    </div>

    {% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <img src="{% static 'images/bannerimage.jpg' %}" height="450px" width="100%">

</div>

<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class ="text-center fw-bold">Our Collection</h3>
    <p style="text-align:justify;line-height:2;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

</div>




<div class="container-fluid">
    <div class="row">
        {% for i in c %}
            <div class="col-md-4 mb-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{i.image.url}}" height="200px" width="100%">
                    <div class="card-body">
                        <h5 class="card-title">{{ i.name }}</h5>
                        <a href="{% url 'shop:prod' i.name %}" class="btn btn-primary">PRODUCTS</a>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/details.html
{% extends 'base.html'%}
{% load static %}
{%block title %}Home{%endblock title%}
{%block content %}
<div class="container">
    <div class="row mt-5">

            <div class="col-sm-4 me-5">

                    <img src="{{j.image.url}}" height="400px" width="400px">

            </div>
            <div class="col-sm-6 me-5">
                <h2>{{j.name}}</h2>

                <p class="h4 mt-5 lh-base">{{j.desc}}</p>
                <h2 class ="mt-5">{{j.price}}</h2>

                {{j.stock}}
                {% if user.is_superuser == True %}
                {% if j.stock == 0 %}
                <h2>OUT OF STOCK</h2>
                <a href="{% url 'admin:index'%}" class="btn btn-danger mt-5">ADD STOCK </a>
                {%  else %}
                <h2>Product in stock</h2>
                <a href="{% url 'admin:index'%}" class="btn btn-danger mt-5">ADD STOCK </a>
                {% endif %}


                {% else %}
                {% if j.stock == 0 %}
                <h2>OUT OF STOCK</h2>
                {%  else %}
                <a href="{% url 'cart:addtocart' j.name %}" class="btn btn-danger mt-5">ADD TO CART </a>
                {% endif %}
             {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
<center>
<h3 class="mt-4">Login</h3></center>

<center><form method ="POST"  >
{% csrf_token %}
<div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">User Name</label>
    <input type="text" class="form-control" name="u" id="exampleInputEmail1" aria-describedby="emailHelp">

  </div>
<div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" name="p" id="exampleInputPassword1">
</div>
   <center><button type="submit" class="btn btn-primary">Submit</button></center>
</form>
</div>
{% endblock %}</center>

ecommerce/templates/orderdetails.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div>

        <h4 class="text-center text-success">{{msg}}</h4>
        <h4 class="text-center text-danger">Thank You !!!!</h4>
        <h4 class="text-center"><a href="{% url 'shop:allcategories' %}">Continue Shopping</a></h4>


</div>

{% endblock %}

ecommerce/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-bottom:100px;">
<center>
    <form method="POST">
      {% csrf_token %}
      <h3 class="mt-4">Order Form</h3>
      <div class="mb-3">
        <label class="form-label">Address</label>
        <input type="text" class="form-control" name="a" placeholder="enter address">
      </div>
       <div class="mb-3">
        <label class="form-label">Phone number</label>
        <input type="number" class="form-control" name="ph" placeholder="enter phonenumber">
      </div>
         <div class="mb-3">
        <label class="form-label">Account number</label>
        <input type="number" class="form-control" name="an" placeholder="enter Account number">
      </div>
        <input type="submit" class="form-control">
    </form>
</center>
</div>
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% for i in o %}
<table border="1" style="text-align: center;">
    <tr>
    <td> Name of the customer : {{u}}</td>
    <td> Product name : {{i.product}}</td>
    <td> Product price : {{i.product.price}}</td>
    <td> Delivery Address : {{i.address}}</td>
    <td> Phone : {{i.phone}}</td>
    <td> No. of Items : {{i.no_of_items}}</td>
    <td> Ordered on : {{i.ordered_date}}</td>
    <td> Delivery status : {{i.delivery_status}}</td>
    </tr>
</table>

{% endfor %}



{% endblock %}

ecommerce/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div>
    <img src="{{ c.image.url }}" height="450px" width="100%">
</div>

<div class="comtainer-fluid mt-3">
    <h3 class="text-center fw-bold" > {{ c.name }}</h3>
    <p style="text-align:justify;line-height:2;"> {{ c.desc }}</p>

</div>


<div class="container-fluid">
    <div class="row">
        {% for i in j %}
            <div class="col-md-4 mb-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{i.image.url}}" height="200px" width="100%">
                    <div class="card-body">
                        <h3 class="card-title">{{ i.name }}</h3>
                        <h5>{{i.price}}</h5>
                        <h5>{{i.category}}</h5>
                        <h5>{{i.stock}}</h5>
                        <h5>{{i.available}}</h5>
                        <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary">BUY</a>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
<center>
<h3 class="mt-4">Register</h3></center>

<form method ="POST"  >
{% csrf_token %}




  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control" name="e" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">User Name</label>
    <input type="text" class="form-control" name="u" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" name="p" id="exampleInputPassword1">
  </div>

    <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Confirm Password</label>
    <input type="password" class="form-control" name="cp" id="exampleInputPassword1">
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label"> First Name</label>
    <input type="text" class="form-control" name="f"  id="exampleInputName" aria-describedby="nameHelp">

    <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Last Name</label>
    <input type="text" class="form-control" name="l"  id="exampleInputName" aria-describedby="nameHelp">


  <button type="submit" class="btn btn-primary">Submit</button>
</form>
  </div>
{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-3" style="margin-bottom:100px;">
<center>

    <h5>you have Searched for {{query}}</h5></center>
    {% if p %}
       <div class="row">
        {% for  i in p %}
            <div class="col-sm-4 " style="margin-right:10px;margin-bottom:10px;">
                <div class="card" style="width: 18rem;">
                    <img src="{{i.image.url}}" height="200px" width="100%">
                    <div class="card-body">
                        <h3 class="card-title">{{ i.name }}</h3>
                        <h5>{{i.price}}</h5>

                        <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary">BUY</a>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
    <h6 class="text-center">No Results</h6>
    {% endif %}


    </div>

    {% endblock %}